services:
  dashboard-devcontainer:
    container_name: iam-dashboard-devcontainer
    image: node:lts
    command: sleep infinity
    depends_on:
      client_registrant:
        condition: service_completed_successfully
    volumes:
      - .:/workspace:cached
      - secrets:/secrets
    environment:
      NEXT_PUBLIC_BASE_PATH: /development
